services:
    db:
        platform: linux/x86_64
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
                MYSQL_DATABASE: 'db'
                MYSQL_ROOT_PASSWORD: 'root'
    app:
        container_name: newsapiapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"